# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  projectbravoapi:
    image: projectbravoapi
    build:
      context: .
      dockerfile: ProjectBravo.Api/Dockerfile
    ports:
      - 8090:8090
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
